GET https://backend-crud-de-filmes.vercel.app/

###

POST https://backend-crud-de-filmes.vercel.app/criarfilme
Content-Type: application/json

{
    "titulo": "Homem-aranha",
    "genero": "Animação/Musical",
    "duracao": "014200",
    "classificacaoEtaria": "12 anos"
}

###
DELETE https://backend-crud-de-filmes.vercel.app/deletarfilme/17

###
PUT https://backend-crud-de-filmes.vercel.app/editarfilme/7
Content-Type: application/json

{
    "titulo": "ANA BANANA",
    "genero": "Ação",
    "duracao": 121000,
    "classificacaoEtaria": "12 anos"
}

###
GET https://backend-crud-de-filmes.vercel.app/todosfilmes

